export const popularAnimalTraits = [
  "Gentle",
  "Affectionate",
  "Playful",
  "Calm",
  "Quiet",
  "Independent",
  "Social",
  "Curious",
  "Active",
  "Energetic",
  "Loyal",
  "Protective",
  "Good with kids",
  "Good with older kids",
  "Good with dogs",
  "Good with cats",
  "Best as only pet",
  "House trained",
  "Lead trained",
  "Crate trained",
  "Apartment friendly",
  "Needs garden",
  "Needs secure yard",
  "Senior friendly",
  "Special needs",
];
